### ISSUE TITLE
Some lute tablature examples of mei contain duplicate xml:ids

### ISSUE THREAD

**Issue by paul-bayleaf** [music-encoding/tablature-ig#7]
A minor issue, but examples/lute/gerle-1552_1-no_4.mei and examples/lute/milano-1546_6-no_8.mei both contain duplicate xml:ids.  xml:ids must be document unique.  See https://www.w3.org/TR/xml-id/ and
https://music-encoding.org/guidelines/v4/content/shared.html#sharedCommonAttributes

gerle-1552_1-no_4.mei contains each of the following xml:ids twice: xml:id='m1.n3', xml:id='m1.n4', xml:id='m1.n5' and xml:id='m6.n6'.

milano-1546_6-no_8.mei contains each of the following xml:ids twice: xml:id='m3.n3' and xml:id='m5.n3'.

In all cases these duplications have occurred as alternatives under a &lt;choice&gt; element; nevertheless each xml:id must still be document unique.

**Comment by reinierdevalk** [comment]
@paul-bayleaf Thanks for pointing this out; now corrected in all examples and the documentation in the branch `update_docs`.
