### ISSUE TITLE
Some lute tablature examples of mei have startid attributes without the required # before the id.

### ISSUE THREAD

**Issue by paul-bayleaf** [music-encoding/tablature-ig#8]
A minor issue, but examples/lute/da_crema-1546_10-no_6.mei, examples/lute/gerle-1552_1-no_4.mei and examples/lute/milano-1546_6-no_8.mei all contain several startid attributes without the required # before the id.  E.g. startid='m1.n3' should be startid='#m1.n3'.

See https://music-encoding.org/guidelines/v4/attribute-classes/att.startid.html att.startId takes a data.URI (rfc2396) as its value.  So a # is needed before the id.

**Comment by reinierdevalk** [comment]
@paul-bayleaf Thanks for this - you are absolutely right. I corrected it (also for all `@endid`s) in all examples, and also in the documentation, in the `update_docs` branch (for which I ill open a pull request soon).
