### ISSUE TITLE
Implement footnotes

### ISSUE THREAD

**Issue by reinierdevalk** [music-encoding/tablature-ig#9]
In the case of adaptations, it would be good to be able to have the information that is enclosed in the `<corr>` part of a `<choice>` element shown in a footnote at the bottom of the page. Perhaps this is already possible in MEI/Verovio; I could not find anything about it.

**Comment by lpugin** [comment]
This is not quite tablature specific. Furthermore, a footnote is very much of a page-like (e.g., printed-like) design approach. In Verovio, everything in editorial markup is preserved as such in the SVG output, which you can use to build an interactive application. You should have a look at this example https://www.verovio.org/tutorial.xhtml?id=topic07. If you really want footnotes, it will be up you the application to put things together.

**Comment by DILewis** [comment]
I agree with @lpugin about this being a general question, and also I do think this is app-specific for live UIs. I do wonder for printed-like design, though. If the page size is fixed, and Verovio does the page layout, how easy would it be for a third-party app to do the necessary work of finding the apparatus, shortening the page at that point, adding the footnote, etc? Not proposing this as a priority for Verovio, but not sure how any other software can do it well in those cases.

**Comment by TimCrawford** [comment]
Can Verovio display ossia passages, which are not so different from this case?
These are effectively system-relative ‘footnotes’ - though usually displayed above the system.
(Of course, I understand that they’re different, but similar in principle.)

T

On 1 Apr 2021, at 10:24, David Lewis ***@***.******@***.***>> wrote:



I agree with @lpugin<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flpugin&data=04%7C01%7Ct.crawford%40gold.ac.uk%7C2460d1b0691a4a37cbf608d8f4effe5a%7C0d431f3f20c1461c958a46b29d4e021b%7C0%7C0%7C637528658902691410%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4MJqu9G74JuF9hcqi5%2BH8OI0BQl9AmkcjJhBssS%2BGXA%3D&reserved=0> about this being a general question, and also I do think this is app-specific for live UIs. I do wonder for printed-like design, though. If the page size is fixed, and Verovio does the page layout, how easy would it be for a third-party app to do the necessary work of finding the apparatus, shortening the page at that point, adding the footnote, etc? Not proposing this as a priority for Verovio, but not sure how any other software can do it well in those cases.

**Comment by lpugin** [comment]
> Can Verovio display ossia passages, which are not so different from this case?

No, it can't. But I cannot see anything in both the encoding and the rendering that seems specific to tablature notation here. If yes, then just add an example.

**Comment by TimCrawford** [comment]
I agree that this is not tablature-specific at all.

T

On 1 Apr 2021, at 10:42, Laurent Pugin ***@***.******@***.***>> wrote:



Can Verovio display ossia passages, which are not so different from this case?

No, it can't. But I cannot see anything in both the encoding and the rendering that seems specific to tablature notation here. If yes, then just add an example.
